function t395_init(recid){var el=$('#rec'+recid);el.find('.t395__tab').click(function(){el.find('.t395__tab').removeClass('t395__tab_active');$(this).addClass('t395__tab_active');t395_alltabs_updateContent(recid);t395_updateSelect(recid);$('.t347').trigger('displayChanged');$('.t346').trigger('displayChanged');$('.t764, .t506, .t675, .t570, .t774, .t397, .t504, .t498, .t778, .t592, .t477, .t480, .t511, .t552, .t132, .t598, .t599, .t650, .t659, .t351, .t353, .t341, .t404, .t385, .t386, .t409, .t384, .t279, .t349, .t433, .t418, .t268, .t428, .t532, .t601, .t478, .t228, .t229, .t456, .t520, .t615, .t517, .t688, .t744, .t609, .t604, .t670, .t686, .t554, .t230, .t486, .t117, .t422, .t616, .t121, .t801, .t412, .t760, .t827, .t829, .t762, .t826, .t734, .t726, .t799').trigger('displayChanged');setTimeout(function(){$('.t351, .t353, .t341, .t404, .t385, .t386, .t409, .t384, .t279, .t349, .t410, .t433, .t418, .t520, .t829').trigger('displayChanged')},50);if(window.lazy=='y'){t_lazyload_update()}});t395_alltabs_updateContent(recid);t395_updateContentBySelect(recid);var bgcolor=el.css("background-color");var bgcolor_target=el.find(".t395__select, .t395__firefoxfix");bgcolor_target.css("background",bgcolor)}
function t395_alltabs_updateContent(recid){var el=$('#rec'+recid);el.find(".t395__tab").each(function(i){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.attr('data-connect-with-tab','yes');rec_el.attr('data-animationappear','off');rec_el.addClass('t379__off')})});el.find(".t395__tab_active").each(function(i){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.removeClass('t379__off');rec_el.css('opacity','')})})}
function t395_updateContentBySelect(recid){var el=$('#rec'+recid);el.find(".t395__select").change(function(){var select_val=el.find(".t395__select").val();var tab_index=el.find(".t395__tab[data-tab-rec-ids='"+select_val+"']");tab_index.trigger('click')})}
function t395_updateSelect(recid){var el=$('#rec'+recid);var current_tab=el.find(".t395__tab_active").attr('data-tab-rec-ids');var el_select=el.find(".t395__select");el_select.val(current_tab)}
function t418_checkSize(recid){var el=$("#rec"+recid);var sizer=el.find('.t418__height');var height=sizer.height();var width=sizer.width();var ratio=width/height;var gallerywrapper=el.find(".t418__checksize");var gallerywidth=gallerywrapper.width();gallerywrapper.css({'height':((gallerywidth/ratio)+'px')});var maxwidth=el.find(".t418__height").width();var windowwidth=$(window).width();var value=windowwidth-80;if(maxwidth>windowwidth){el.find(".t418__item").css("max-width",value+"px");el.find(".t418__img").css("left","20px");el.find(".t418__img").css("right","20px")}else{el.find(".t418__item").css("max-width","");el.find(".t418__img").css("left","");el.find(".t418__img").css("right","")}}
function t418_init(recid){var el=$('#rec'+recid);var pos=0;var t418_doResize;var totalSlides=el.find('.t418__item').length;var sliderWidth=el.find('.t418__item').width();$(window).resize(function(){if(t418_doResize)clearTimeout(t418_doResize);t418_doResize=setTimeout(function(){sliderWidth=el.find('.t418__slider').width();el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);console.log(sliderWidth)},200)});el.find('.t418__slidecontainer').width(sliderWidth*totalSlides);el.find('.t418__next').click(function(){slideRight(recid)});el.find('.t418__previous').click(function(){slideLeft(recid)});function slideLeft(recid){var el=$('#rec'+recid);pos--;if(pos==-1){pos=totalSlides-1}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
function slideRight(recid){var el=$('#rec'+recid);pos++;if(pos==totalSlides){pos=0}
el.find('.t418__slidecontainer').css({transform:'translate(-'+(sliderWidth*pos)+'px, 0)'})
el.find('.t418__slidecontainer').css("transition-duration",".3s");if(window.lazy=='y'){t_lazyload_update()}}
var swipeOptions={triggerOnTouchEnd:!0,swipeStatus:swipeStatus,allowPageScroll:"vertical",threshold:75};el.find(".t418__slidecontainer").swipe(swipeOptions);el.find(".t418__slidecontainer").swipe({tap:function(event,target){slideRight(recid)}});function swipeStatus(event,phase,direction,distance){if(phase=="move"&&(direction=="left"||direction=="right")){var duration=0;if(direction=="left"){scrollImages((sliderWidth*pos)+distance,duration)}else if(direction=="right"){scrollImages((sliderWidth*pos)-distance,duration)}}else if(phase=="cancel"){scrollImages(sliderWidth*pos)}else if(phase=="end"){if(direction=="right"){slideLeft(recid)}else if(direction=="left"){slideRight(recid)}}}
function scrollImages(distance,duration){el.find(".t418__slidecontainer").css("transition-duration",(duration/1000).toFixed(1)+"s");var value=(distance<0?"":"-")+Math.abs(distance).toString();el.find(".t418__slidecontainer").css("transform","translate("+value+"px, 0)")}}
function t509_setHeight(recid){var t509__el=$("#rec"+recid);var t509__image=t509__el.find(".t509__blockimg");t509__image.each(function(){var t509__width=$(this).attr("data-image-width");var t509__height=$(this).attr("data-image-height");var t509__ratio=t509__height/t509__width;var t509__padding=t509__ratio*100;$(this).css("padding-bottom",t509__padding+"%")});if($(window).width()>960){var t509__textwr=t509__el.find(".t509__textwrapper");var t509__deskimg=t509__el.find(".t509__desktopimg");t509__textwr.each(function(){$(this).css("height",t509__deskimg.innerHeight())})}}
function t533_equalHeight(recid){var el=$('#rec'+recid);el.find('.t533').css('visibility','visible');el.find('.t533__textwrapper').css('height','auto');$('#rec'+recid+' .t533__row').each(function(){var highestBox=0;$('.t533__textwrapper',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t533__textwrapper',this).css('height',highestBox)}else{$('.t533__textwrapper',this).css('height',"auto")}})};function t592_init(recid){var element=$('#rec'+recid).find('.t592__descr');var highestBox=0;element.css('height','');element.each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){element.css('height',highestBox)}else{element.css('height','')}};function t609_setHeight(recid){var el=$("#rec"+recid);var image=el.find(".t609__bgimg");image.each(function(){var width=$(this).attr("data-image-width");var height=$(this).attr("data-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t609_init(recid){var el=$('#rec'+recid),element=el.find('.t609__descr'),highestBox=0;element.css('height','');element.each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){element.css('height',highestBox)}else{element.css('height','')}}
function t821_init(recid){var rec=$('#rec'+recid);var el=rec.find('.t821');var isFixed=(el.css('position')=='fixed');var redactorMode=el.hasClass('t821_redactor-mode');if(!redactorMode){el.removeClass('t821__beforeready');if(isFixed&&el.attr('data-bgopacity-two')){t821_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t821_changebgopacitymenu(recid)},200))}
if(isFixed&&el.attr('data-appearoffset')){el.removeClass('t821__beforeready');t821_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t821_appearMenu(recid)},200))}}
t821_setBg(recid);$(window).bind('resize',t_throttle(function(){t821_setBg(recid)},200))}
function t821_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t821_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t821_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t821_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t821"),burger=el.find(".t821__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t821_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t825_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t825__popup'),analitics=el.attr('data-track-popup'),hook="TildaSendMessageWidget"+recid,obj=$('#rec'+recid+' .t825__btn');obj.click(function(e){if(obj.hasClass("t825__btn_active")){t825_closePopup();return}
obj.addClass("t825__btn_active");$('#rec'+recid+' .t825').addClass("t825_active");t825_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}});if(window.lazy=='y'){t_lazyload_update()}
t825_checkPhoneNumber(recid)}
function t825_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t825__popup');$('.t825__btn_wrapper').removeClass('t825__btn_animate');$('.t825__btn-text').css('display','none');if($(window).width()<960){$('body').addClass('t825__body_popupshowed')}
popup.css('display','block');setTimeout(function(){popup.addClass('t825__popup_show')},50);el.find(".t825__mobile-icon-close").click(function(e){t825_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t825_closePopup()}});if(window.lazy=='y'){t_lazyload_update()}}
function t825_closePopup(){if($(window).width()<960){$('body').removeClass('t825__body_popupshowed')}
$('.t825').removeClass("t825_active");$('.t825__btn').removeClass('t825__btn_active');$('.t825__popup').removeClass('t825__popup_show');setTimeout(function(){$('.t825__popup').not('.t825__popup_show').css('display','none')},300)}
function t825_checkPhoneNumber(recid){var el=$('#rec'+recid);var whatsapp=el.find('.t825__whatsapp').attr('href');var telegram=el.find('.t825__telegram').attr('href');var vk=el.find('.t825__vk').attr('href');var skype=el.find('.t825__skype').attr('href');var mail=el.find('.t825__mail').attr('href');var viber=el.find('.t825__viber').attr('href');var fb=el.find('.t825__fb').attr('href');var phone=el.find('.t825__phone').attr('href');if(typeof whatsapp!='undefined'){el.find('.t825__whatsapp').attr('href','https://api.whatsapp.com/send?phone='+whatsapp.replace(/[+?^${}()|[\]\\\s]/g,''))}
el.find('.t825__telegram').attr('href','https://t.me/'+telegram);el.find('.t825__vk').attr('href','https://vk.me/'+vk);if(typeof skype!='undefined'){el.find('.t825__skype').attr('href','skype:'+skype.replace(/[+?^${}()|[\]\\\s]/g,''))}
if(typeof viber!='undefined'){el.find('.t825__viber').attr('href','viber://chat?number=%2B'+viber.replace(/[+?^${}()|[\]\\\s]/g,''))}
el.find('.t825__mail').attr('href','mailto:'+mail);el.find('.t825__fb').attr('href','https://m.me/'+fb);if(typeof phone!='undefined'){el.find('.t825__phone').attr('href','tel:+'+phone.replace(/[+?^${}()|[\]\\\s]/g,''))}}
function t825_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}